export const inputClasses = [
  "container",
  "container-active",
  "tracking-widest",
  "border-2",
  "block",
  "px-2.5",
  "pb-2.5",
  "pt-4",
  "pl-6",
  "w-full",
  "text-sm",
  "dark:text-gray-300",
  "text-gray-900",
  "bg-transparent",
  "rounded-full",
  "border-1",
  "border-gray-300",
  "appearance-none",
  // "dark:border-slate-500",
  "focus:outline-none",
  "focus:ring-0",
  // "focus:border-sky-500",
  "peer"
];

export const inputLabelClasses = [
  "tracking-widest",
  "absolute",
  "text-sm",
  "text-gray-500",
  "dark:text-gray-400",
  "duration-300",
  "transform",
  "-translate-y-4",
  "scale-75",
  "top-2",
  "z-10",
  "origin-[0]",
  "bg-white",
  "dark:bg-gray-900",
  "px-2",
  "ml-3",
  "peer-focus:px-2",
  // "peer-focus:text-sky-500",
  // "peer-focus:dark:text-sky-500",
  "peer-placeholder-shown:scale-100",
  "peer-placeholder-shown:-translate-y-1/2",
  "peer-placeholder-shown:top-1/2",
  "peer-focus:top-2",
  "peer-focus:scale-75",
  "peer-focus:-translate-y-4",
  "left-1",
  "peer",
];
